# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sqlite_db

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sqlite_db

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sqlite_db/CMakeFiles /home/sqlite_db/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sqlite_db/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named repl

# Build rule for target.
repl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 repl
.PHONY : repl

# fast build rule for target.
repl/fast:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/build
.PHONY : repl/fast

execute.o: execute.c.o

.PHONY : execute.o

# target to build an object file
execute.c.o:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/execute.c.o
.PHONY : execute.c.o

execute.i: execute.c.i

.PHONY : execute.i

# target to preprocess a source file
execute.c.i:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/execute.c.i
.PHONY : execute.c.i

execute.s: execute.c.s

.PHONY : execute.s

# target to generate assembly for a file
execute.c.s:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/execute.c.s
.PHONY : execute.c.s

repl.o: repl.c.o

.PHONY : repl.o

# target to build an object file
repl.c.o:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/repl.c.o
.PHONY : repl.c.o

repl.i: repl.c.i

.PHONY : repl.i

# target to preprocess a source file
repl.c.i:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/repl.c.i
.PHONY : repl.c.i

repl.s: repl.c.s

.PHONY : repl.s

# target to generate assembly for a file
repl.c.s:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/repl.c.s
.PHONY : repl.c.s

row.o: row.c.o

.PHONY : row.o

# target to build an object file
row.c.o:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/row.c.o
.PHONY : row.c.o

row.i: row.c.i

.PHONY : row.i

# target to preprocess a source file
row.c.i:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/row.c.i
.PHONY : row.c.i

row.s: row.c.s

.PHONY : row.s

# target to generate assembly for a file
row.c.s:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/row.c.s
.PHONY : row.c.s

table.o: table.c.o

.PHONY : table.o

# target to build an object file
table.c.o:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/table.c.o
.PHONY : table.c.o

table.i: table.c.i

.PHONY : table.i

# target to preprocess a source file
table.c.i:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/table.c.i
.PHONY : table.c.i

table.s: table.c.s

.PHONY : table.s

# target to generate assembly for a file
table.c.s:
	$(MAKE) -f CMakeFiles/repl.dir/build.make CMakeFiles/repl.dir/table.c.s
.PHONY : table.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... repl"
	@echo "... execute.o"
	@echo "... execute.i"
	@echo "... execute.s"
	@echo "... repl.o"
	@echo "... repl.i"
	@echo "... repl.s"
	@echo "... row.o"
	@echo "... row.i"
	@echo "... row.s"
	@echo "... table.o"
	@echo "... table.i"
	@echo "... table.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

